language: node_js
node_js: stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules
#before_install:
#  - npm install -g hexo-cli
# Start: Build Lifecycle
install:
  - npm install
# 执行清缓存，生成网页操作
script:
  - npm run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "lennon"
  - git config user.email "kbjwdh@gmail.com"
  - git add .
  - git commit -m "Update by travis ci"
  - git push --force --quiet "https://${ACCESS_TOKEN}@${GH_REF}" master:gh-pages
# End: Build LifeCycle
branches:
  only:
    - master
